version: '3'
services:
  afs_demo:
    build: 
      context: docker/
      dockerfile: Dockerfile
    entrypoint: /docker-entrypoint.sh
    environment:
      - CRAWL_DOMAINS=${CRAWL_DOMAINS}
      - CRAWL_START_URL=${CRAWL_START_URL}
      - AFS_CLOUD_EMBEDDING=${AFS_CLOUD_EMBEDDING}
      - API_KEY_EMBEDDING=${API_KEY_EMBEDDING}
      - AFS_CLOUD_FFM=${AFS_CLOUD_FFM}
      - API_KEY_FFM=${API_KEY_FFM}
      - FFM_MODEL_NAME=${FFM_MODEL_NAME}
      - ENDPOINT_EMBEDDING=${AFS_CLOUD_EMBEDDING}/embeddings/api/embeddings
      - ENDPOINT_FFM=${AFS_CLOUD_FFM}/text-generation/api/models/generate
    ports:
      - 80:80
    volumes:
      - .:/home/ubuntu/AFS_tools/use_cases/webcrawler_chatbot
volumes:
  embedding_folder:
